package net.logandark.camerashake.api.provider;

import net.logandark.camerashake.api.event.CameraShakeEvent;
import net.minecraft.client.network.ClientPlayerEntity;

/**
 * As opposed to {@link CameraShakeEvent}s, which are created on demand and are
 * generally short-lived, providers are always present. Use providers for things
 * like camera shake based on proximity to something. Providers are passed the
 * player entity, while events are only passed the time since their addition.
 */
public interface CameraShakeProvider {
	/**
	 * @param player The local player
	 * @return The magnitude in blocks of the camera shake being generated by
	 * this provider
	 */
	double getCameraShakeMagnitude(ClientPlayerEntity player);
}
